apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
  namespace: project
spec:
  metrics:
    - name: cpu-usage-rate
      interval: 1m
      count: 10
      successCondition: result < 0.5
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-operated:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="project"}[1m])) > 0.5
