apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backend-deployment.yaml
  - manifests/backend-service.yaml
  - manifests/ingress.yaml
  - manifests/loki-backend-config.yaml
  - manifests/postgres-config.yaml
  - manifests/postgres-deployment.yaml
  - manifests/postgres-pvc.yaml
  - manifests/postgres-pv.yaml
  - manifests/postgres-secret.yaml
  - manifests/postgres-service.yaml
  - manifests/todo-deployment.yaml
  - manifests/todo-service.yaml

