apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backend-rollout.yaml
  - manifests/backend-service.yaml
  - manifests/ingress.yaml
  - manifests/loki-backend-config.yaml
  - manifests/postgres-config.yaml
  - manifests/postgres-deployment.yaml
  - manifests/postgres-pvc.yaml
  - manifests/postgres-pv.yaml
  - manifests/postgres-secret.yaml
  - manifests/postgres-service.yaml
  - manifests/todo-rollout.yaml
  - manifests/todo-service.yaml
  - manifests/hpa-todo.yaml
  - manifests/hpa-todo-backend.yaml
  - manifests/hpa-todo-db.yaml
  - manifests/cpu-usage-check.yaml

