apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: log-output-service
spec:
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

